Read in 3d magnetic field datacube, and compute relative field-line helicity in minimal gauge.

Use this to compute the total relative helicity $H_r$ by integrating over all six boundaries, and compare this to the direct volume integration of $H_r$ (in both DeVore-Coulomb and minimal gauges).

In [ ]:
import numpy as np
from flhcart import BField
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
from mpl_toolkits.mplot3d import Axes3D
import time

Create 3d magnetic field object

- creating this object automatically computes A in the DeVore-Coulomb gauge.

In [ ]:
b = BField('bhesse.nc')

Computing A...


Compute potential reference field and its vector potential

In [ ]:
b.computePotentialField()
b.computeADeVore(potential=True)

Computing potential field...
Computing Ap...


Compute relative helicity directly by volume integration

In [ ]:
Hr0 = b.relativeHelicity()
print('Hr from volume integration (DeVore-Coulomb upward gauge) = %g' % Hr0)

Hr from volume integration (DeVore-Coulomb upward gauge) = -2.97565e+07


Change both vector potentials to minimal gauge

- alternatively, you could just change $\bf A_p$, then match $\bf A$ to it with `b.matchPotentialGauge()`.

In [ ]:
b.matchUniversalGauge()
b.matchUniversalGauge(potential=True)

Matching Axn to universal gauge on each boundary...
Matching Apxn to universal gauge on each boundary...


array([[[ 0.00000000e+00, -2.64648330e+01, -6.18336293e+01, ...,
         -6.63776010e+03, -6.72424259e+03, -6.79637950e+03],
        [ 5.94572608e+00, -2.93281403e+01, -7.04895738e+01, ...,
         -6.62870575e+03, -6.72250227e+03, -6.80994202e+03],
        [ 1.77453164e+01, -2.63038805e+01, -7.40657552e+01, ...,
         -6.62669325e+03, -6.72711874e+03, -6.82508965e+03],
        ...,
        [-7.59867500e+02, -8.12253548e+02, -8.70840816e+02, ...,
         -8.82674379e+03, -8.93799468e+03, -9.04430243e+03],
        [-7.84942432e+02, -8.28521947e+02, -8.81315022e+02, ...,
         -8.91629321e+03, -9.02172138e+03, -9.11746677e+03],
        [-8.00000055e+02, -8.35576784e+02, -8.84220923e+02, ...,
         -9.01537303e+03, -9.11513085e+03, -9.19637967e+03]],

       [[ 9.48943147e+01,  6.92975166e+01,  3.66273619e+01, ...,
         -6.15236092e+03, -6.21979165e+03, -6.26456111e+03],
        [ 1.12065981e+02,  7.79262172e+01,  3.73316867e+01, ...,
         -6.33835771e+03, -6.40894841e

Compute relative helicity directly by volume integration

In [ ]:
Hr = b.relativeHelicity()
print('Hr from volume integration (minimal gauge) = %g' % Hr)

Hr from volume integration (minimal gauge) = -2.97565e+07


Compute relative helicity from relative field-line helicity

map of FLH on $z=\text{const.}$

In [ ]:
nx = b.nx
ny = b.ny
x1 = np.linspace(b.x1[0], b.x1[-1], nx)
y1 = np.linspace(b.y1[0], b.y1[-1], ny)
x1s, y1s = np.meshgrid(x1,y1, indexing='ij')

map of FLH on lower boundary $z = 0$

In [ ]:
z1s = x1s*0
print(f"z = {z1s}")
x0 = np.stack((x1s.flatten(), y1s.flatten(), z1s.flatten()), axis=1)
bz0 = np.abs(b.bz(x1s, y1s, z1s))
flh_z0 = b.flHelicity(x0) - b.flHelicity(x0, potential=True)
flh_z0 = flh_z0.reshape(nx, ny)

z = [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
Tracing 4096 field lines...
Tracing 4096 field lines...


map of FLH on top boundary $z = 40$

In [ ]:
z1s = x1s*0 + b.z1[-1]
print(f"z = {z1s}")
x0 = np.stack((x1s.flatten(), y1s.flatten(), z1s.flatten()), axis=1)
bz1 = np.abs(b.bz(x1s, y1s, z1s)) 
flh_z1 = b.flHelicity(x0) - b.flHelicity(x0, potential=True)
flh_z1 = flh_z1.reshape(nx, ny)

z = [[40. 40. 40. ... 40. 40. 40.]
 [40. 40. 40. ... 40. 40. 40.]
 [40. 40. 40. ... 40. 40. 40.]
 ...
 [40. 40. 40. ... 40. 40. 40.]
 [40. 40. 40. ... 40. 40. 40.]
 [40. 40. 40. ... 40. 40. 40.]]
Tracing 4096 field lines...
Tracing 4096 field lines...


map of FLH on $x=\text{const.}$

In [ ]:
ny = b.ny
nz = b.nz
y1 = np.linspace(b.y1[0], b.y1[-1], ny)
z1 = np.linspace(b.z1[0], b.z1[-1], nz)
y1s, z1s = np.meshgrid(y1,z1, indexing='ij')

map of FLH on right boundary $x = 20$

In [ ]:
x1s = y1s*0 + b.x1[-1]
print(f"x = {x1s}")
x0 = np.stack((x1s.flatten(), y1s.flatten(), z1s.flatten()), axis=1)
bx1 = np.abs(b.bx(x1s, y1s, z1s)) 
flh_x1 = b.flHelicity(x0) - b.flHelicity(x0, potential=True)
flh_x1 = flh_x1.reshape(ny, nz)

x = [[20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 ...
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]]
Tracing 4096 field lines...
Tracing 4096 field lines...


map of FLH on left boundary $x = -20$

In [ ]:
x1s = y1s*0 + b.x1[0]
print(f"x = {x1s}")
x0 = np.stack((x1s.flatten(), y1s.flatten(), z1s.flatten()), axis=1)
bx0 = np.abs(b.bx(x1s, y1s, z1s))
flh_x0 = b.flHelicity(x0) - b.flHelicity(x0, potential=True)
flh_x0 = flh_x0.reshape(ny, nz)   

x = [[-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]
 ...
 [-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]]
Tracing 4096 field lines...
Tracing 4096 field lines...


map of FLH on $y=\text{const.}$

In [ ]:
nx = b.nx
nz = b.nz
x1 = np.linspace(b.x1[0], b.x1[-1], nx)
z1 = np.linspace(b.z1[0], b.z1[-1], nz)
x1s, z1s = np.meshgrid(x1,z1, indexing='ij')

map of FLH on top boundary $y = 20$

In [ ]:
y1s = x1s*0 + b.y1[-1]
print(f"y = {y1s}")
x0 = np.stack((x1s.flatten(), y1s.flatten(), z1s.flatten()), axis=1)
by1 = np.abs(b.by(x1s, y1s, z1s))
flh_y1 = b.flHelicity(x0) - b.flHelicity(x0, potential=True)
flh_y1 = flh_y1.reshape(nx, nz)

y = [[20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 ...
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]
 [20. 20. 20. ... 20. 20. 20.]]
Tracing 4096 field lines...
Tracing 4096 field lines...


map of FLH on bottom boundary $y = -20$

In [ ]:
y1s = x1s*0 + b.y1[0]
print(f"y = {y1s}")
x0 = np.stack((x1s.flatten(), y1s.flatten(), z1s.flatten()), axis=1)
by0 = np.abs(b.by(x1s, y1s, z1s))
flh_y0 = b.flHelicity(x0) - b.flHelicity(x0, potential=True)
flh_y0 = flh_y0.reshape(nx, nz)

y = [[-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]
 ...
 [-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]
 [-20. -20. -20. ... -20. -20. -20.]]
Tracing 4096 field lines...
Tracing 4096 field lines...


estimate total helicity by adding FLH over all field lines

In [ ]:
print(flh_z0.shape)
print(flh_z0)

(64, 64)
[[ -755.12568015  -807.60644694  -844.75211838 ...     0.
      0.             0.        ]
 [ -763.52417969  -812.53440398  -851.59822427 ...  -296.03467739
   -304.29691309  -301.91460474]
 [ -765.82593531  -817.34158095  -857.71217534 ...  -984.07626324
  -1012.422859   -1081.50355487]
 ...
 [-1080.95335464 -1017.99287947  -986.48613573 ...  -853.42344323
   -810.33036414  -768.56966988]
 [ -302.36650927  -305.8793551   -297.77567732 ...  -844.12664182
   -802.57126528  -765.89593099]
 [    0.             0.             0.         ...  -840.69994313
   -797.61712235  -755.86858931]]


In [ ]:
print(bz0.shape)
print(bz0)

(64, 64)
[[18.97594531 18.3650794  17.73015876 ... 19.7301587  20.36507933
  19.97594531]
 [19.47442682 19.36507937 18.73015873 ... 18.73015873 19.36507937
  19.47442682]
 [19.47124435 19.36507937 18.73015873 ... 18.73015873 19.36507937
  19.47124435]
 ...
 [19.47124435 19.36507937 18.73015873 ... 18.73015873 19.36507937
  19.47124435]
 [19.47442682 19.36507937 18.73015873 ... 18.73015873 19.36507937
  19.47442682]
 [19.97594531 20.36507933 19.7301587  ... 17.73015876 18.3650794
  18.97594531]]


Add up all field lines and divide by two (each should be counted twice)

$$
\frac{1}{2}\oint_{\partial V}\mathcal{A}_{\rm R}|B_n|\,\mathrm{d}^2x = H_{\rm R},
$$

$$
\int \int \mathrm{d}x \mathrm{d}y
$$

In [ ]:
hf = np.trapz(np.trapz(flh_z0*bz0, x=x1, axis=0), x=y1, axis=0)
hf += np.trapz(np.trapz(flh_z1*bz1, x=x1, axis=0), x=y1, axis=0)

$$
\int \int \mathrm{d}y \mathrm{d}z
$$

In [ ]:
hf += np.trapz(np.trapz(flh_x0*bx0, x=y1, axis=0), x=z1, axis=0)  
hf += np.trapz(np.trapz(flh_x1*bx1, x=y1, axis=0), x=z1, axis=0)

$$
\int \int \mathrm{d}x \mathrm{d}z
$$

In [ ]:
hf += np.trapz(np.trapz(flh_y0*by0, x=x1, axis=0), x=z1, axis=0)   
hf += np.trapz(np.trapz(flh_y1*by1, x=x1, axis=0), x=z1, axis=0)

In [ ]:
hf /= 2

In [ ]:
print('Hr from relative FLH (minimal gauge) = %g' % hf)

Hr from relative FLH (minimal gauge) = -2.95275e+07


Compare

In [ ]:
print('Hr from volume integration (DeVore-Coulomb upward gauge) = %g' % Hr0)
print('Hr from volume integration (minimal gauge) = %g' % Hr)
print('Hr from relative FLH (minimal gauge) = %g' % hf)

Hr from volume integration (DeVore-Coulomb upward gauge) = -2.97565e+07
Hr from volume integration (minimal gauge) = -2.97565e+07
Hr from relative FLH (minimal gauge) = -2.95275e+07
